trigger:
  - main

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:r)

variables:
  solution: "EdiEnergyViewer.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

jobs:
  - job: Build
    timeoutInMinutes: 15
    pool:
      vmImage: "windows-latest"
    steps:
      - task: UseDotNet@2
        inputs:
          version: 9.x

      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: "6.12.1"

      - task: DotNetCoreCLI@2
        displayName: "Restore nuget packages"
        inputs:
          command: "restore"
          projects: "$(solution)"
          restoreArguments: "--runtime win-x64"

      - task: NodeTool@0
        inputs:
          versionSpec: "22.x"
        displayName: "[Client] Install Node.js"

      - task: PowerShell@2
        displayName: "[Client] npm install"
        inputs:
          targetType: "inline"
          script: "npm install"
          workingDirectory: "edienergyviewer.client"

      - task: DotNetCoreCLI@2
        displayName: "[Server] Enforcing code style"
        inputs:
          command: "custom"
          custom: "format"
          projects: 'EdiEnergyViewer.Server\EdiEnergyViewer.Server.csproj'
          arguments: "-v d --verify-no-changes --no-restore"

      - task: DotNetCoreCLI@2
        displayName: "[Server] Publish GUI into output"
        inputs:
          command: "publish"
          publishWebProjects: false
          projects: 'EdiEnergyViewer.Server\EdiEnergyViewer.Server.csproj'
          arguments: "-c $(buildConfiguration) -o output --no-self-contained --runtime win-x64"
          zipAfterPublish: false
          modifyOutputPath: false
          workingDirectory: "$(System.DefaultWorkingDirectory)"

      - task: PublishBuildArtifacts@1
        displayName: "Publish output"
        inputs:
          PathtoPublish: "output"
          ArtifactName: "drop"
          publishLocation: "Container"
